### ISSUE TITLE
links to downloads of toolbox and TLA Proof System

### ISSUE THREAD

**Issue by omouse** [hwayne/learntla#27]
it would be nice if the guide included a link (preferably direct) to downloading the IDE and proof system:

* http://lamport.azurewebsites.net/tla/toolbox.html
* http://tla.msr-inria.inria.fr/tlaps/content/Home.html

It felt like a chore to dig out the right links to download the tools.

**Comment by hwayne** [comment]
Which page where you on when you ran into this issue? There's a direct link on [about this guide](https://learntla.com/introduction/about-this-guide/) and [using the toolbox](https://learntla.com/pluscal/toolbox/), but if it sounds like you were on a different page (or those links weren't obvious enough).

Followup thought: what if instead of linking to the toolbox page, I linked to the [release page](https://github.com/tlaplus/tlaplus/releases)?

**Comment by hwayne** [comment]
...It was the [example page](https://learntla.com/introduction/example/), wasn't it :(

**Comment by omouse** [comment]
lol yes, it was the example page, but also the introduction page, something like "download X and Y and Z before we begin" would be nice to see there.

Release page would work, anything to get the reader to download the tool before they start reading.

**Comment by hwayne** [comment]
Should be fixed now. Did not add the TLAPS link; I think the proof system is outside the scope of the guide.

**Comment by omouse** [comment]
Thanks for fixing it!
